### ISSUE TITLE
mass[i] ^= mass[j] ^= mass[i] ^= mass[j];

### ISSUE THREAD

**Issue by marcfedorow** [EdikGres/Lab-work-3-dop#2]
https://github.com/EdikGres/Lab-work-3-dop/blob/5196ebbec4bbde00ecb12f713a741adc17f23ad9/Lab-work-3-dop/MyLibForLab.cpp#L7-L9

**Comment by EdikGres** [comment]
Thanks for the comment, the repository is old, there is no desire to update. Sorry.
YOU TOP BRO <3
